### ISSUE TITLE
Install from local directory or zip

### ISSUE THREAD

**Issue by pemontto** [w33ble/kbn-shoehorn#3]
I've found some plugins where the repo won't work and I need to download the release file and install from the zip.
Is it possible to install from a downloaded zip file. I tried using file:/// without any luck.

Another alternative is to provide a URL to a zip file, though that may be difficult to discern from a custom repo URL.

**Comment by w33ble** [comment]
If you already have the zip file, or a url to it, you can just use the build in `bin/kibana-plugin` command to install the plugin. Does that not work for some reason?

**Comment by pemontto** [comment]
I have to manually unzip, change the version number and zip again before running the command.

**Comment by w33ble** [comment]
Ahhhh, I see. You might be able to skip the re-zipping part and just point kbn-shoehorn at the path, but I'm probably wrong about that (hence your ask). That part's pretty easy to add, I'll do that soon. 

The zip detection might be a little trickier, but I'll look into it.

**Comment by w33ble** [comment]
@pemontto master supports installing from a local path, so you can grab that if you need this immediately. I still need to add local zip support, and once I do I'll cut a new version. After that, I can work on being able to install from a zip URL directly.

**Comment by w33ble** [comment]
OK, zip support is in there, and I just published v0.3.0 on npm.

I also opened #7 to track using a zip from a URL, and I'm going to close this issue. Thanks for another useful suggestion!

**Comment by pemontto** [comment]
🥇 amazing!
