### ISSUE TITLE
Replace extract-zip

### ISSUE THREAD

**Issue by w33ble** [w33ble/kbn-shoehorn#6]
This package is using a fork.

It's using a pretty outdated version of `debug`, but is has a vulnerable version of `ms`. Open PRs on the repo have been open for a while, and the tests do not pass on Mac (though, the failure is only related to error messages).

**Comment by pemontto** [comment]
Can't currently install kbn-shoehorn without access to the fork:

```
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.10.3
npm info addNameTag [ 'kbn-shoehorn', 'latest' ]
npm info attempt registry request try #1 at 11:43:39 PM
npm http request GET https://registry.npmjs.org/@w33ble%2fextract-zip
npm http 404 https://registry.npmjs.org/@w33ble%2fextract-zip
npm ERR! Linux 4.4.59-1-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "-g" "install" "kbn-shoehorn" "-d"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @w33ble/extract-zip
npm ERR! 404 
npm ERR! 404  '@w33ble/extract-zip' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'kbn-shoehorn'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by w33ble** [comment]
Oh shoot, I probably published that as private. My bad. I'll fix it a little later today once I'm in front of a computer.

**Comment by w33ble** [comment]
v0.3.1 published, should be fixed. There was a permissions thing, but also I never fixed the require statement when I changed to the fork :(.

**Comment by w33ble** [comment]
Using [the unzip code from Kibana](https://github.com/elastic/kibana/blob/master/src/cli_plugin/install/zip.js#L68-L126) is probably good enough.
